---
title: "Biostatistique"
base: teaching.qmd
tbl-colwidths: [5,10,15,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

::: column-body
| **Semaine** |  **Date**  | **Chapitre**                       |               **Lectures**                |                                                    **Diapos**                                                     |                **Activités**                |                        **TD**                        |
|:---------:|:---------:|:----------|:---------:|:---------:|:---------:|:---------:|
|    **1**    | 2023-12-12 | Théorie des Ensembles              | [{{< fa book >}}](#){.unclickable-button} |      [{{< fa file-powerpoint >}}](slides/theorie_des_ensembles.pdf "Théorie des Ensembles"){target="_blank"}      | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **2**    | 2023-12-12 | Analyse Combinatoire               | [{{< fa book >}}](#){.unclickable-button} |       [{{< fa file-powerpoint >}}](slides/analyse_combinatoire.pdf "Analyse Combinatoire"){target="_blank"}       | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **3**    | 2023-12-12 | Probabilité Conditionnelle         | [{{< fa book >}}](#){.unclickable-button} | [{{< fa file-powerpoint >}}](slides/probabilite_conditionnelle.pdf "Probabilité Conditionnelle"){target="_blank"} | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **4**    | 2023-12-12 | Lois Discrètes                     | [{{< fa book >}}](#){.unclickable-button} |             [{{< fa file-powerpoint >}}](slides/lois_discretes.pdf "Lois Discrètes"){target="_blank"}             | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **5**    | 2023-12-12 | Lois Continues                     | [{{< fa book >}}](#){.unclickable-button} |             [{{< fa file-powerpoint >}}](slides/lois_continues.pdf "Lois Continues"){target="_blank"}             | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **6**    | 2023-12-12 | Échantillonnage                    | [{{< fa book >}}](#){.unclickable-button} |             [{{< fa file-powerpoint >}}](#){.unclickable-button}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **7**    | 2023-12-12 | Estimation                         | [{{< fa book >}}](#){.unclickable-button} |                               [{{< fa file-powerpoint >}}](#){.unclickable-button}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **8**    | 2023-12-12 | Tests d'hypothèse (1 échantillon)  | [{{< fa book >}}](#){.unclickable-button} |             [{{< fa file-powerpoint >}}](slides/tests_un_echantillon.pdf "Tests d'Hypothese I"){target="_blank"}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|    **9**    | 2023-12-12 | Tests d'hypothèse (2 échantillons) | [{{< fa book >}}](#){.unclickable-button} |                               [{{< fa file-powerpoint >}}](slides/tests_deux_echantillons.pdf "Tests d'Hypothese II"){target="_blank"}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|   **10**    | 2023-12-12 | Tests d'hypothèse ($k$ échantillons)    | [{{< fa book >}}](#){.unclickable-button} |                               [{{< fa file-powerpoint >}}](slides/tests_k_echantillons.pdf "Tests d'Hypothese III"){target="_blank"}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|   **11**    | 2023-12-12 | Corrélation et Régression          | [{{< fa book >}}](#){.unclickable-button} |                               [{{< fa file-powerpoint >}}](#){.unclickable-button}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
|   **12**    | 2023-12-12 | Application sur R                  | [{{< fa book >}}](#){.unclickable-button} |                               [{{< fa file-powerpoint >}}](#){.unclickable-button}                                | [{{< fa laptop >}}](#){.unclickable-button} | [{{< fa users-rectangle >}}](#){.unclickable-button} |
:::
